// STAR WARS CANON ARCHIVE — DATA
// Only official canon: the Skywalker Saga, anthology films, and canon
// animated/live-action series. No Legends/EU material, no non-canon anthologies.

const SW_DATA = [

  // ===================== SKYWALKER SAGA =====================
  {
    id: "tpm",
    title: "The Phantom Menace",
    subtitle: "Episode I",
    year: 1999,
    type: "movie",
    era: "prequel",
    order: 1,
    runtime: "136 min",
    director: "George Lucas",
    summary: "A Jedi Master and his apprentice are sent to resolve a trade dispute that hides a far larger conspiracy. On Tatooine they discover a gifted slave boy named Anakin Skywalker, while a young queen fights to free her homeworld of Naboo from occupation.",
    tags: ["Jedi Order", "Naboo", "Sith Return"]
  },
  {
    id: "aotc",
    title: "Attack of the Clones",
    subtitle: "Episode II",
    year: 2002,
    type: "movie",
    era: "prequel",
    order: 2,
    runtime: "142 min",
    director: "George Lucas",
    summary: "A decade later, Anakin Skywalker has grown into a headstrong Jedi apprentice. As a separatist movement threatens the Republic, he is assigned to protect Senator Padmé Amidala — and a secret army of clones is revealed to be waiting in the shadows.",
    tags: ["Clone Army", "Separatists", "Forbidden Love"]
  },
  {
    id: "rots",
    title: "Revenge of the Sith",
    subtitle: "Episode III",
    year: 2005,
    type: "movie",
    era: "prequel",
    order: 3,
    runtime: "140 min",
    director: "George Lucas",
    summary: "The Clone Wars rage across the galaxy as Chancellor Palpatine tightens his grip on power. Consumed by fear and ambition, Anakin Skywalker falls to the dark side, becoming Darth Vader, as the Jedi Order is destroyed and the Empire rises.",
    tags: ["Order 66", "Fall of Anakin", "Birth of the Empire"]
  },
  {
    id: "anh",
    title: "A New Hope",
    subtitle: "Episode IV",
    year: 1977,
    type: "movie",
    era: "original",
    order: 4,
    runtime: "121 min",
    director: "George Lucas",
    summary: "The film that started it all. A farm boy on a desert planet finds a droid carrying stolen plans, meets an old Jedi hermit, and joins a smuggler and a princess in a desperate attempt to destroy the Empire's ultimate weapon: the Death Star.",
    tags: ["Death Star", "Rebellion", "Origin"]
  },
  {
    id: "esb",
    title: "The Empire Strikes Back",
    subtitle: "Episode V",
    year: 1980,
    type: "movie",
    era: "original",
    order: 5,
    runtime: "124 min",
    director: "Irvin Kershner",
    summary: "The Empire hunts the scattered Rebel fleet across the galaxy. Luke Skywalker travels to a remote swamp world to train with the Jedi Master Yoda, while his friends are betrayed on Cloud City and Luke learns a truth that will change everything.",
    tags: ["Yoda", "Cloud City", "The Reveal"]
  },
  {
    id: "rotj",
    title: "Return of the Jedi",
    subtitle: "Episode VI",
    year: 1983,
    type: "movie",
    era: "original",
    order: 6,
    runtime: "131 min",
    director: "Richard Marquand",
    summary: "Luke Skywalker returns to rescue Han Solo from Jabba the Hutt before facing his final test: confronting Darth Vader and the Emperor himself, as the Rebel fleet launches an all-out assault on the second Death Star above the forest moon of Endor.",
    tags: ["Redemption", "Endor", "Second Death Star"]
  },
  {
    id: "tfa",
    title: "The Force Awakens",
    subtitle: "Episode VII",
    year: 2015,
    type: "movie",
    era: "sequel",
    order: 7,
    runtime: "138 min",
    director: "J.J. Abrams",
    summary: "Thirty years after the fall of the Empire, a scavenger named Rey, a defected stormtrooper named Finn, and ace pilot Poe Dameron are drawn into a new conflict against the First Order and its enforcer, the conflicted Kylo Ren.",
    tags: ["First Order", "New Heroes", "Legacy"]
  },
  {
    id: "tlj",
    title: "The Last Jedi",
    subtitle: "Episode VIII",
    year: 2017,
    type: "movie",
    era: "sequel",
    order: 8,
    runtime: "152 min",
    director: "Rian Johnson",
    summary: "Rey seeks out the self-exiled Luke Skywalker, hoping he will help her find a way to restore hope to a galaxy in crisis. Meanwhile the Resistance, badly outgunned, fights a desperate rearguard retreat from the ruthless First Order.",
    tags: ["Luke's Exile", "Resistance", "Sacrifice"]
  },
  {
    id: "tros",
    title: "The Rise of Skywalker",
    subtitle: "Episode IX",
    year: 2019,
    type: "movie",
    era: "sequel",
    order: 9,
    runtime: "142 min",
    director: "J.J. Abrams",
    summary: "The surviving Resistance faces the First Order once more as the reemergence of a long-thought-dead enemy sends Rey, Finn, and Poe on a race across the galaxy to uncover the truth of Rey's past and end the conflict once and for all.",
    tags: ["Palpatine Returns", "Final Battle", "Saga's End"]
  },

  // ===================== ANTHOLOGY FILMS =====================
  {
    id: "rogueone",
    title: "Rogue One: A Star Wars Story",
    subtitle: "Anthology Film",
    year: 2016,
    type: "movie",
    era: "anthology",
    order: 3.5,
    runtime: "133 min",
    director: "Gareth Edwards",
    summary: "A ragtag group of Rebel agents, led by Jyn Erso, undertake a desperate mission to steal the plans for the Empire's new superweapon — a mission that sets the events of A New Hope directly into motion.",
    tags: ["Death Star Plans", "Rebel Sacrifice", "Precedes A New Hope"]
  },
  {
    id: "solo",
    title: "Solo: A Star Wars Story",
    subtitle: "Anthology Film",
    year: 2018,
    type: "movie",
    era: "anthology",
    order: 3.6,
    runtime: "135 min",
    director: "Ron Howard",
    summary: "A young Han Solo falls in with a crew of smugglers, meets Chewbacca and Lando Calrissian, and makes the legendary Kessel Run — the origin story of the galaxy's most famous scoundrel.",
    tags: ["Han's Origin", "Kessel Run", "Chewbacca & Lando"]
  },
  {
    id: "tcw-film",
    title: "Star Wars: The Clone Wars",
    subtitle: "Animated Film",
    year: 2008,
    type: "movie",
    era: "prequel",
    order: 2.5,
    runtime: "98 min",
    director: "Dave Filoni",
    summary: "Anakin Skywalker takes on a new Jedi Padawan, Ahsoka Tano, and the pair are sent to rescue Jabba the Hutt's kidnapped son — a mission that doubled as the theatrical pilot for the long-running animated series.",
    tags: ["Ahsoka Introduced", "Clone Wars Era"]
  },

  // ===================== ANIMATED SERIES =====================
  {
    id: "series-tcw",
    title: "Star Wars: The Clone Wars",
    subtitle: "Animated Series",
    year: "2008–2020",
    type: "series",
    era: "prequel",
    order: 2.7,
    seasons: "7 Seasons",
    creator: "Dave Filoni",
    summary: "The definitive chronicle of the Clone Wars, following Anakin Skywalker, Obi-Wan Kenobi, and Ahsoka Tano through the war that will ultimately consume the Republic — widely regarded as essential viewing for understanding Anakin's fall.",
    tags: ["Ahsoka Tano", "Republic vs. Separatists"]
  },
  {
    id: "series-rebels",
    title: "Star Wars Rebels",
    subtitle: "Animated Series",
    year: "2014–2018",
    type: "series",
    era: "original",
    order: 3.8,
    seasons: "4 Seasons",
    creator: "Dave Filoni",
    summary: "Set in the years before A New Hope, a small crew aboard the starship Ghost — led by the Jedi Kanan Jarrus and his Padawan Ezra Bridger — becomes one of the sparks that ignites the galaxy-wide Rebellion against the Empire.",
    tags: ["Early Rebellion", "Ghost Crew", "Thrawn"]
  },
  {
    id: "series-resistance",
    title: "Star Wars Resistance",
    subtitle: "Animated Series",
    year: "2018–2020",
    type: "series",
    era: "sequel",
    order: 6.5,
    seasons: "2 Seasons",
    creator: "Dave Filoni",
    summary: "Young pilot Kazuda Xiono goes undercover for the Resistance at a remote outpost, gathering intelligence on the growing First Order threat in the years leading up to The Force Awakens.",
    tags: ["First Order Spies", "Pre-Force Awakens"]
  },
  {
    id: "series-badbatch",
    title: "Star Wars: The Bad Batch",
    subtitle: "Animated Series",
    year: "2021–2024",
    type: "series",
    era: "prequel",
    order: 3.2,
    seasons: "3 Seasons",
    creator: "Jennifer Corbett",
    summary: "In the immediate aftermath of Order 66, an elite squad of genetically unique clones — Clone Force 99 — struggles to find their place in a galaxy now ruled by the newborn Empire.",
    tags: ["Clone Force 99", "Early Empire"]
  },
  {
    id: "series-totj",
    title: "Tales of the Jedi",
    subtitle: "Animated Anthology",
    year: 2022,
    type: "series",
    era: "prequel",
    order: 2.3,
    seasons: "1 Season, 6 Shorts",
    creator: "Dave Filoni",
    summary: "A collection of animated shorts exploring pivotal moments in the lives of Ahsoka Tano and Count Dooku, from a Jedi's earliest days as a Youngling to a fateful turn toward the dark side.",
    tags: ["Origin Stories", "Ahsoka & Dooku"]
  },
  {
    id: "series-tote",
    title: "Tales of the Empire",
    subtitle: "Animated Anthology",
    year: 2024,
    type: "series",
    era: "original",
    order: 3.9,
    seasons: "1 Season, 6 Shorts",
    creator: "Dave Filoni",
    summary: "Short stories following Morgan Elsbeth's path from conquered Nightsister to Imperial agent, and former Jedi Barriss Offee's uneasy survival under the Empire's watchful eye.",
    tags: ["Imperial Agents", "Fallen Jedi"]
  },
  {
    id: "series-yja",
    title: "Star Wars: Young Jedi Adventures",
    subtitle: "Animated Series",
    year: "2023–",
    type: "series",
    era: "highrepublic",
    order: 0.5,
    seasons: "Ongoing",
    creator: "James Waugh",
    summary: "Set during the High Republic era, this series for younger viewers follows a group of Jedi Younglings learning the ways of the Force at the Jedi Temple on Tenoo, generations before the Skywalker saga begins.",
    tags: ["High Republic", "Young Audience"]
  },

  {
    id: "series-acolyte",
    title: "The Acolyte",
    subtitle: "Live-Action Series",
    year: 2024,
    type: "series",
    era: "highrepublic",
    order: 0.8,
    seasons: "1 Season",
    creator: "Leslye Headland",
    summary: "Set in the final days of the High Republic, a former Padawan is pulled back into conflict with her old Jedi Master when a mysterious assailant begins targeting Jedi across the galaxy, unearthing secrets from her past.",
    tags: ["High Republic", "Jedi Investigation"]
  },

  // ===================== LIVE-ACTION SERIES =====================
  {
    id: "series-mando",
    title: "The Mandalorian",
    subtitle: "Live-Action Series",
    year: "2019–",
    type: "series",
    era: "newrepublic",
    order: 9.1,
    seasons: "3 Seasons",
    creator: "Jon Favreau",
    summary: "A lone bounty hunter operating on the outer reaches of the galaxy takes on a mysterious job that leads him to a small, Force-sensitive foundling — and a fierce determination to protect him at any cost.",
    tags: ["Grogu", "Bounty Hunter", "New Republic Era"]
  },
  {
    id: "series-bobf",
    title: "The Book of Boba Fett",
    subtitle: "Live-Action Series",
    year: 2021,
    type: "series",
    era: "newrepublic",
    order: 9.2,
    seasons: "1 Season",
    creator: "Jon Favreau",
    summary: "The legendary bounty hunter Boba Fett and mercenary Fennec Shand stake their claim on the criminal underworld of Tatooine, attempting to rule the territory once controlled by Jabba the Hutt.",
    tags: ["Tatooine", "Criminal Underworld"]
  },
  {
    id: "series-obiwan",
    title: "Obi-Wan Kenobi",
    subtitle: "Limited Series",
    year: 2022,
    type: "series",
    era: "original",
    order: 3.7,
    seasons: "1 Season",
    creator: "Deborah Chow",
    summary: "Ten years after the fall of the Jedi Order, a haunted and self-exiled Obi-Wan Kenobi watches over young Luke Skywalker from afar — until a mission draws him into a direct confrontation with his former apprentice, Darth Vader.",
    tags: ["Vader Rematch", "Exile"]
  },
  {
    id: "series-andor",
    title: "Andor",
    subtitle: "Live-Action Series",
    year: "2022–2025",
    type: "series",
    era: "original",
    order: 3.4,
    seasons: "2 Seasons",
    creator: "Tony Gilroy",
    summary: "A grounded, espionage-driven look at how the Rebellion against the Empire truly began, following small-time thief Cassian Andor as he is pulled into a growing resistance movement — leading directly into the events of Rogue One.",
    tags: ["Rebel Origins", "Espionage", "Precedes Rogue One"]
  },
  {
    id: "series-ahsoka",
    title: "Ahsoka",
    subtitle: "Live-Action Series",
    year: "2023–",
    type: "series",
    era: "newrepublic",
    order: 9.3,
    seasons: "1 Season",
    creator: "Dave Filoni",
    summary: "Former Jedi Ahsoka Tano investigates a growing threat to the fragile New Republic, uncovering a plot to bring back the exiled Grand Admiral Thrawn from the far reaches of the galaxy.",
    tags: ["Thrawn Returns", "New Republic Threats"]
  },
  {
    id: "series-skeletoncrew",
    title: "Star Wars: Skeleton Crew",
    subtitle: "Live-Action Series",
    year: "2024–",
    type: "series",
    era: "newrepublic",
    order: 9.4,
    seasons: "1 Season",
    creator: "Jon Watts & Christopher Ford",
    summary: "Four kids from a quiet suburban planet stumble onto a buried starship and find themselves lost in a strange and dangerous galaxy, desperately trying to find their way back home.",
    tags: ["Kids on an Adventure", "New Republic Era"]
  },
];

// Era metadata for filtering & visual theming
const SW_ERAS = {
  highrepublic: { label: "High Republic", color: "#7dd3fc" },
  prequel:      { label: "Prequel Era",     color: "#e8c468" },
  original:     { label: "Original Trilogy", color: "#4fc3f7" },
  anthology:    { label: "Anthology",       color: "#ff8c42" },
  newrepublic:  { label: "New Republic Era", color: "#8fd694" },
  sequel:       { label: "Sequel Era",       color: "#ff5c5c" },
};
